/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import java.awt.Dimension;
import java.beans.PropertyVetoException;

/**
 *
 * @author mucha
 */
public class FormUtama extends javax.swing.JFrame {
    public static FormBarang formBarang;
    public static FormJenisBarang formJenisBarang;
    public static FormSupplier formSupplier;
    public static FormPetugas formPetugas;
    public static FormBarangKeluar formBarangKeluar;
    public static FormBarangMasuk formBarangMasuk;
    public static FormLaporanBarangKeluar formLaporanBarangKeluar;
    public static FormLaporanBarangMasuk formLaporanBarangMasuk;
    public FormLogin formLogin = new FormLogin(this, true);
    private final PesanDialog pesanDialog = new PesanDialog();
    /**
     * Creates new form FormDashboard
     */
    public FormUtama() {
        initComponents();
        setEnableMenu(false);
    }
    
    private void setEnableMenu(boolean aktif){
        masterMenu.setEnabled(aktif);
        transaksiMenu.setEnabled(aktif);
        laporanMenu.setEnabled(aktif);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mdiDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        deskripsiMenuItem = new javax.swing.JMenuItem();
        loginMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        keluarMenuItem = new javax.swing.JMenuItem();
        masterMenu = new javax.swing.JMenu();
        barangMenuItem = new javax.swing.JMenuItem();
        jenisBarangMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        supplierMenuItem = new javax.swing.JMenuItem();
        petugasMenuItem = new javax.swing.JMenuItem();
        transaksiMenu = new javax.swing.JMenu();
        barangMasukMenuItem = new javax.swing.JMenuItem();
        barangKeluarMenuItem = new javax.swing.JMenuItem();
        laporanMenu = new javax.swing.JMenu();
        laporanBarangMasukMenuItem = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produksi Barang");

        javax.swing.GroupLayout mdiDesktopPaneLayout = new javax.swing.GroupLayout(mdiDesktopPane);
        mdiDesktopPane.setLayout(mdiDesktopPaneLayout);
        mdiDesktopPaneLayout.setHorizontalGroup(
            mdiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        mdiDesktopPaneLayout.setVerticalGroup(
            mdiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        jMenu1.setText("Aplikasi");

        deskripsiMenuItem.setText("Deskripsi");
        jMenu1.add(deskripsiMenuItem);

        loginMenuItem.setText("Login");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(loginMenuItem);
        jMenu1.add(jSeparator1);

        keluarMenuItem.setText("Keluar");
        keluarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(keluarMenuItem);

        jMenuBar1.add(jMenu1);

        masterMenu.setText("Master Data");

        barangMenuItem.setText("Barang");
        barangMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(barangMenuItem);

        jenisBarangMenuItem.setText("Jenis Barang");
        jenisBarangMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisBarangMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(jenisBarangMenuItem);
        masterMenu.add(jSeparator2);

        supplierMenuItem.setText("Supplier");
        supplierMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(supplierMenuItem);

        petugasMenuItem.setText("Petugas");
        petugasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petugasMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(petugasMenuItem);

        jMenuBar1.add(masterMenu);

        transaksiMenu.setText("Transaksi");

        barangMasukMenuItem.setText("Barang Masuk");
        barangMasukMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangMasukMenuItemActionPerformed(evt);
            }
        });
        transaksiMenu.add(barangMasukMenuItem);

        barangKeluarMenuItem.setText("Barang Keluar");
        barangKeluarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangKeluarMenuItemActionPerformed(evt);
            }
        });
        transaksiMenu.add(barangKeluarMenuItem);

        jMenuBar1.add(transaksiMenu);

        laporanMenu.setText("Laporan");

        laporanBarangMasukMenuItem.setText("Laporan Barang Masuk");
        laporanBarangMasukMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanBarangMasukMenuItemActionPerformed(evt);
            }
        });
        laporanMenu.add(laporanBarangMasukMenuItem);

        jMenuItem7.setText("Laporan Barang Keluar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        laporanMenu.add(jMenuItem7);

        jMenuBar1.add(laporanMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarMenuItemActionPerformed

    private void barangMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangMenuItemActionPerformed
        // TODO add your handling code here:
         if((formBarang != null) && formBarang.isVisible()){
            try{
                formBarang.setSelected(true);
            }catch (PropertyVetoException ex){}
        }else{
            formBarang = new FormBarang();
            mdiDesktopPane.add(formBarang);
            formBarang.setVisible(true);
        }
    }//GEN-LAST:event_barangMenuItemActionPerformed

    private void jenisBarangMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisBarangMenuItemActionPerformed
        // TODO add your handling code here:
        if((formJenisBarang != null) && formJenisBarang.isVisible()){
            try{
                formJenisBarang.setSelected(true);
            }catch (PropertyVetoException ex){}
        }else{
            formJenisBarang = new FormJenisBarang();
            mdiDesktopPane.add(formJenisBarang);
            formJenisBarang.setVisible(true);
        }
    }//GEN-LAST:event_jenisBarangMenuItemActionPerformed

    private void supplierMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierMenuItemActionPerformed
        // TODO add your handling code here:
        if((formSupplier != null) && formSupplier.isVisible()){
            try{
                formSupplier.setSelected(true);
            }catch (PropertyVetoException ex){}
        }else{
            formSupplier = new FormSupplier();
            mdiDesktopPane.add(formSupplier);
            formSupplier.setVisible(true);
        }
    }//GEN-LAST:event_supplierMenuItemActionPerformed

    private void petugasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petugasMenuItemActionPerformed
        // TODO add your handling code here:
        if((formPetugas != null) && formPetugas.isVisible()){
            try{
                formPetugas.setSelected(true);
            }catch (PropertyVetoException ex){}
        }else{
            formPetugas = new FormPetugas();
            mdiDesktopPane.add(formPetugas);
            formPetugas.setVisible(true);
        }
    }//GEN-LAST:event_petugasMenuItemActionPerformed

    private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuItemActionPerformed
        // TODO add your handling code here:
        if(loginMenuItem.getText().equals("Login")){
            formLogin.setVisible(true);
            if(!formLogin.getUserLogin().equals("")){
                setEnableMenu(true);
                loginMenuItem.setText("Logout");
            }else{
                setEnableMenu(false);
            }
        }else{
           if (pesanDialog.tampilkanPilihan("Apakah anda yakin ingin Logout?" ,"Konfirmasi", new Object[]{"Ya","Tidak"}) == 0){
                setEnableMenu(false);
                loginMenuItem.setText("Login");
           }
        }
    }//GEN-LAST:event_loginMenuItemActionPerformed

    private void barangKeluarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangKeluarMenuItemActionPerformed
        // TODO add your handling code here:
        if((formBarangKeluar != null) && formBarangKeluar.isVisible()){
            try{
                formBarangKeluar.setSelected(true);
            }catch (PropertyVetoException ex){}
        }else{
            formBarangKeluar = new FormBarangKeluar();
            mdiDesktopPane.add(formBarangKeluar);
            formBarangKeluar.setVisible(true);
        }
    }//GEN-LAST:event_barangKeluarMenuItemActionPerformed

    private void barangMasukMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangMasukMenuItemActionPerformed
        // TODO add your handling code here:
        if((formBarangMasuk != null) && formBarangMasuk.isVisible()){
            try{
                formBarangMasuk.setSelected(true);
            }catch (PropertyVetoException ex){}
        }else{
            formBarangMasuk = new FormBarangMasuk();
            mdiDesktopPane.add(formBarangMasuk);
            formBarangMasuk.setVisible(true);
        }
    }//GEN-LAST:event_barangMasukMenuItemActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        if((formLaporanBarangKeluar != null) && formLaporanBarangKeluar.isVisible()){
            try{
                formLaporanBarangKeluar.setSelected(true);
            }catch(PropertyVetoException ex){}
        }else{
            formLaporanBarangKeluar = new FormLaporanBarangKeluar();
            mdiDesktopPane.add(formLaporanBarangKeluar);
            formLaporanBarangKeluar.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void laporanBarangMasukMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanBarangMasukMenuItemActionPerformed
        // TODO add your handling code here:
        if((formLaporanBarangMasuk != null) && formLaporanBarangMasuk.isVisible()){
            try{
                formLaporanBarangMasuk.setSelected(true);
            }catch(PropertyVetoException ex){}
        }else{
            formLaporanBarangMasuk = new FormLaporanBarangMasuk();
            mdiDesktopPane.add(formLaporanBarangMasuk);
            formLaporanBarangMasuk.setVisible(true);
        }
    }//GEN-LAST:event_laporanBarangMasukMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem barangKeluarMenuItem;
    private javax.swing.JMenuItem barangMasukMenuItem;
    private javax.swing.JMenuItem barangMenuItem;
    private javax.swing.JMenuItem deskripsiMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem jenisBarangMenuItem;
    private javax.swing.JMenuItem keluarMenuItem;
    private javax.swing.JMenuItem laporanBarangMasukMenuItem;
    private javax.swing.JMenu laporanMenu;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JMenu masterMenu;
    private javax.swing.JDesktopPane mdiDesktopPane;
    private javax.swing.JMenuItem petugasMenuItem;
    private javax.swing.JMenuItem supplierMenuItem;
    private javax.swing.JMenu transaksiMenu;
    // End of variables declaration//GEN-END:variables
}
